insert into SeattleArt.dbo.Art_Style values ('Temp', 'Technology', 'Micronesian');
insert into SeattleArt.dbo.Art_Style values ('Zamit', 'Energy', 'Houma');
insert into SeattleArt.dbo.Art_Style values ('Hatity', 'Basic Industries', 'Potawatomi');
insert into SeattleArt.dbo.Art_Style values ('Mat Lam Tam', 'Consumer Services', 'Yaqui');
insert into SeattleArt.dbo.Art_Style values ('Regrant', 'n/a', 'Ecuadorian');
insert into SeattleArt.dbo.Art_Style values ('Latlux', 'Finance', 'Mexican');
insert into SeattleArt.dbo.Art_Style values ('Ventosanzap', 'Consumer Services', 'Chinese');
insert into SeattleArt.dbo.Art_Style values ('Job', 'n/a', 'Argentinian');
insert into SeattleArt.dbo.Art_Style values ('Fintone', 'Capital Goods', 'Choctaw');
insert into SeattleArt.dbo.Art_Style values ('Sonair', 'Health Care', 'Ottawa');
insert into SeattleArt.dbo.Art_Style values ('Stronghold', 'Public Utilities', 'Laotian');
insert into SeattleArt.dbo.Art_Style values ('Konklab', 'Consumer Services', 'Fijian');
insert into SeattleArt.dbo.Art_Style values ('Vagram', 'Finance', 'Thai');
insert into SeattleArt.dbo.Art_Style values ('Namfix', 'Consumer Services', 'Indonesian');
insert into SeattleArt.dbo.Art_Style values ('Stringtough', 'Basic Industries', 'Asian Indian');
insert into SeattleArt.dbo.Art_Style values ('Bytecard', 'Technology', 'Costa Rican');
insert into SeattleArt.dbo.Art_Style values ('Gembucket', 'n/a', 'Polynesian');
insert into SeattleArt.dbo.Art_Style values ('Bitwolf', 'n/a', 'Chamorro');
insert into SeattleArt.dbo.Art_Style values ('Konklux', 'Health Care', 'Tlingit-Haida');
insert into SeattleArt.dbo.Art_Style values ('Konklab', 'Finance', 'Alaska Native');